## input
ops_intent:
  infrastructure:
    anycast_sid_locator_block: fc00:ff00::/24
    nodes:
    - { name: l1, type: lb , locator: fc00:0201::/32 } # no locator used
    - { name: l2, type: lb , locator: fc00:0202::/32 } # no locator used
    - { name: n1, type: nat, locator: fc00:0301::/32 }
    - { name: n2, type: nat, locator: fc00:0302::/32 }
    - { name: n3, type: nat, locator: fc00:0303::/32 }
    - { name: n4, type: nat, locator: fc00:0304::/32 }
    - { name: n5, type: nat, locator: fc00:0305::/32 }
  functions:
  - { name: NAT1, nat: { vip: 142.0.0.1, replicas: 3 }}
  - { name: NAT2, nat: { vip: 142.0.0.2, replicas: 3 }}
  - { name: NAT3, nat: { vip: 142.0.0.3, replicas: 3 }}
  - { name: NAT4, nat: { vip: 142.0.0.4, replicas: 3 }}
  - { name: NAT5, nat: { vip: 142.0.0.5, replicas: 3 }}

## output
nodeConfig:
- name: L1
  config:
    localSids:
    - sid: fc00:ff01:0001::0/48 # NAT1
      End_MFL:
        backends:
        - fc00:0301:0001::0
        - fc00:0301:0002::0
        - fc00:0301:0003::0
    - sid: fc00:ff01:0002::0/48 # NAT2
      End_MFL:
        backends:
        - fc00:0301:0002::0
        - fc00:0301:0003::0
        - fc00:0301:0004::0
    - sid: fc00:ff01:0003::0/48 # NAT3
      End_MFL:
        backends:
        - fc00:0301:0003::0
        - fc00:0301:0004::0
        - fc00:0301:0005::0
    - sid: fc00:ff01:0004::0/48 # NAT4
      End_MFL:
        backends:
        - fc00:0301:0004::0
        - fc00:0301:0005::0
        - fc00:0301:0001::0
    - sid: fc00:ff01:0005::0/48 # NAT5
      End_MFL:
        backends:
        - fc00:0301:0005::0
        - fc00:0301:0001::0
        - fc00:0301:0002::0

- name: L2
  config:
    localSids:
    - sid: fc00:ff01:0001::0/48 # NAT1
      End_MFL:
        backends:
        - fc00:0301:0001::0
        - fc00:0301:0002::0
        - fc00:0301:0003::0
    - sid: fc00:ff01:0002::0/48 # NAT2
      End_MFL:
        backends:
        - fc00:0301:0002::0
        - fc00:0301:0003::0
        - fc00:0301:0004::0
    - sid: fc00:ff01:0003::0/48 # NAT3
      End_MFL:
        backends:
        - fc00:0301:0003::0
        - fc00:0301:0004::0
        - fc00:0301:0005::0
    - sid: fc00:ff01:0004::0/48 # NAT4
      End_MFL:
        backends:
        - fc00:0301:0004::0
        - fc00:0301:0005::0
        - fc00:0301:0001::0
    - sid: fc00:ff01:0005::0/48 # NAT5
      End_MFL:
        backends:
        - fc00:0301:0005::0
        - fc00:0301:0001::0
        - fc00:0301:0002::0

- name: N1
  config:
    localSids:
    - { sid: fc00:0301:0001::/48, End_MFN: { vip: 142.0.0.1 }}
    - { sid: fc00:0301:0004::/48, End_MFN: { vip: 142.0.0.4 }}
    - { sid: fc00:0301:0005::/48, End_MFN: { vip: 142.0.0.5 }}

- name: N2
  config:
    localSids:
    - { sid: fc00:0301:0001::/48, End_MFN: { vip: 142.0.0.1 }}
    - { sid: fc00:0301:0002::/48, End_MFN: { vip: 142.0.0.2 }}
    - { sid: fc00:0301:0005::/48, End_MFN: { vip: 142.0.0.5 }}

- name: N3
  config:
    localSids:
    - { sid: fc00:0301:0001::/48, End_MFN: { vip: 142.0.0.1 }}
    - { sid: fc00:0301:0002::/48, End_MFN: { vip: 142.0.0.2 }}
    - { sid: fc00:0301:0003::/48, End_MFN: { vip: 142.0.0.3 }}

- name: N4
  config:
    localSids:
    - { sid: fc00:0301:0002::/48, End_MFN: { vip: 142.0.0.2 }}
    - { sid: fc00:0301:0003::/48, End_MFN: { vip: 142.0.0.3 }}
    - { sid: fc00:0301:0004::/48, End_MFN: { vip: 142.0.0.4 }}

- name: N5
  config:
    localSids:
    - { sid: fc00:0301:0003::/48, End_MFN: { vip: 142.0.0.3 }}
    - { sid: fc00:0301:0004::/48, End_MFN: { vip: 142.0.0.4 }}
    - { sid: fc00:0301:0005::/48, End_MFN: { vip: 142.0.0.5 }}
