ops_intent:
  infrastructure:
    anycast_sid_locator_block: fc00:ff00::/24
    nodes:
    - { name: l1, type: lb , locator: fc00:0201::/32 } # no locator used
    - { name: l2, type: lb , locator: fc00:0202::/32 } # no locator used
    - { name: n1, type: nat, locator: fc00:0301::/32 }
    - { name: n2, type: nat, locator: fc00:0302::/32 }
    - { name: n3, type: nat, locator: fc00:0303::/32 }
    - { name: n4, type: nat, locator: fc00:0304::/32 }
    - { name: n5, type: nat, locator: fc00:0305::/32 }
  functions:
  - { name: NAT1, nat: { vip: 142.0.0.1, replicas: 3 }}
  - { name: NAT2, nat: { vip: 142.0.0.2, replicas: 3 }}
  - { name: NAT3, nat: { vip: 142.0.0.3, replicas: 3 }}
  - { name: NAT4, nat: { vip: 142.0.0.4, replicas: 3 }}
  - { name: NAT5, nat: { vip: 142.0.0.5, replicas: 3 }}
