maxRules: 17
maxBackends: 10
localSids:
- sid: fc00:1:1::/48 # NAT1
  End_MFL:
    backends:
    - fc00:11:1::1
    - fc00:12:1::1
- sid: fc00:1:2::/48 # NAT1
  End_MFL:
    backends:
    - fc00:12:1::1
    - fc00:13:1::1
