namePrefix: l1
maxRules: 1
maxBackends: 7
encapSource: fc00:1::0
localSids:
- sid: fc00:ff01::/32 # NAT1
  End_MFL:
    vip: 142.0.0.1
    natPortHashBit: 0x00ff
    uSidBlock: fc00::0
    uSidBlockLength: 16
    uSidFunctionLength: 16
    uSidFunctionRevisions:
    # - backends:
    #   - 1301::0
    # - backends:
    #   - 1101::0
    #   - 1201::0
    #   - 1301::0
    - backends:
      - 1101::0
      - 1201::0
