namePrefix: l2
maxRules: 2
maxBackends: 7
encapSource: fc00:2::0
localSids:
- sid: fc00:ff:1::/48 # NAT1
  End_MFL:
    vip: 142.0.0.1
    uSidBlock: fc00::0
    uSidBlockLength: 16
    uSidFunctionLength: 32
    uSidFunctionRevisions:
    - backends:
      - 0011:0001::0
    - backends:
      - 0011:0001::0
      - 0012:0001::0
      - 0013:0001::0
    - backends:
      - 0011:0001::0
      - 0012:0001::0
