namePrefix: n1
encapSource: fc00:11::0
localSids:
- sid: fc00:11:1::/48 # NAT1
  End_MFN_NAT:
    vip: 142.0.0.1
    natPortHashBit: 0xff00
    sources:
    - 10.254.0.10/32
fib4:
- prefix: 10.254.0.10/24
  action:
    encapSeg6:
      mode: encap
      segs:
      - fc00:201:1::0
