namePrefix: n3
encapSource: fc00:3300::0
localSids:
- sid: fc00:3301::/32 # NAT1
  End_MFN_NAT:
    vip: 142.0.0.1
    natPortHashBit: 0x00ff
    uSidBlockLength: 16
    uSidFunctionLength: 16
    sources:
    - 10.0.1.0/24
fib4:
- prefix: 10.0.1.0/24
  action:
    encapSeg6:
      mode: encap
      segs:
      - fc00:1101::0
