namePrefix: n3
encapSource: fc00:13::0
localSids:
- sid: fc00:13:1::/48 # NAT1
  End_MFN_NAT:
    vip: 142.0.0.1
    natPortHashBit: 0x00ff
    sources:
    - 10.254.0.10/32
fib4:
- prefix: 10.254.0.10/24
  action:
    encapSeg6:
      mode: encap
      segs:
      - fc00:201:1::0
