{
 "title": "Main",
 "time": { "from": "now-3m", "to": "now" },
 "refresh": "1s",
 "panels": [
  { "title": "Packet Processing Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "irate RX PPS (eno12399)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_packets_total{device=\"eno12399\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "irate TX PPS (eno12399)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(node_network_transmit_packets_total{device=\"eno12399\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "irate RX BPS (eno12399)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"eno12399\"}[1m]) * 8",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "irate TX BPS (eno12399)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{device=\"eno12399\"}[1m]) * 8",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "irate RX-Drop PPS (eno12399)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_drop_total{device=\"eno12399\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "irate TX-Drop PPS (eno12399)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(node_network_transmit_drop_total{device=\"eno12399\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}