instances:
- name: l1
  netns: L1
  interface: net0
  maxRules: 2
  maxBackends: 7
  encapSource: fc00:2100::0
  localSids:
  - sid: fc00:ff01::/32 # NAT1
    End_MFL:
      vip: 142.0.0.1
      natPortHashBit: 0x00ff
      natMapping: endpointIndependentMapping
      natFiltering: endpointIndependentFiltering
      uSidBlock: fc00::0
      uSidBlockLength: 16
      uSidFunctionLength: 16
      uSidFunctionRevisions:
      - backends: [3201::0]
      - backends: [3101::0]
      - backends: [3201::0]
  - sid: fc00:ff02::/32 # NAT2
    End_MFL:
      vip: 142.0.0.2
      natPortHashBit: 0x00ff
      natMapping: endpointIndependentMapping
      natFiltering: endpointIndependentFiltering
      uSidBlock: fc00::0
      uSidBlockLength: 16
      uSidFunctionLength: 16
      uSidFunctionRevisions:
      - backends:
        - 3102::0
        - 3202::0
        - 3302::0
