# permissions for end users to edit nats.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: nat-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cplane
    app.kubernetes.io/part-of: cplane
    app.kubernetes.io/managed-by: kustomize
  name: nat-editor-role
rules:
- apiGroups:
  - mfplane.mfplane.io
  resources:
  - nats
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mfplane.mfplane.io
  resources:
  - nats/status
  verbs:
  - get
