FROM grafana/grafana-enterprise:10.3.3
COPY ./cmd/grafana/provisioning /etc/grafana/provisioning
COPY ./cmd/grafana/dashboards /var/lib/grafana/dashboards
COPY ./cmd/grafana/grafana.ini /etc/grafana/grafana.ini
