apiVersion: mfplane.mfplane.io/v1alpha1
kind: Node
metadata:
  labels:
    app.kubernetes.io/name: node
    app.kubernetes.io/instance: node-sample
    app.kubernetes.io/part-of: cplane
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cplane
  name: node-sample1
spec:
  hostname: common
  functions:
  - name: L1
    netns: l1
    device: net0
    type: clb
    mode: xdpgeneric
    labels:
      lbGroup: lbGroup1
      lbMaxRules: "2"
      lbMaxBackends: "7"
    segmentRoutingSrv6:
      encapSource: fc00:2100::0
      locators:
      - name: default
        prefix: fc00:2100::/24
        block: fc00::0
      - name: anycast
        prefix: fc00:ff00::/24
        block: fc00::0
        anycast: true
  - name: L2
    netns: l2
    device: net0
    type: clb
    mode: xdpgeneric
    labels:
      lbGroup: lbGroup1
      lbMaxRules: "2"
      lbMaxBackends: "7"
    segmentRoutingSrv6:
      encapSource: fc00:2200::0
      locators:
      - name: default
        prefix: fc00:2200::/24
        block: fc00::0
      - name: anycast
        prefix: fc00:ff00::/24
        block: fc00::0
        anycast: true
  - name: L3
    netns: l3
    device: net0
    type: clb
    mode: xdpgeneric
    labels:
      lbGroup: lbGroup1
      lbMaxRules: "2"
      lbMaxBackends: "7"
    segmentRoutingSrv6:
      encapSource: fc00:2300::0
      locators:
      - name: default
        prefix: fc00:2300::/24
        block: fc00::0
      - name: anycast
        prefix: fc00:ff00::/24
        block: fc00::0
        anycast: true
  - name: L4
    netns: l4
    device: net0
    type: clb
    mode: xdpgeneric
    labels:
      lbGroup: lbGroup1
      lbMaxRules: "2"
      lbMaxBackends: "7"
    segmentRoutingSrv6:
      encapSource: fc00:2400::0
      locators:
      - name: default
        prefix: fc00:2400::/24
        block: fc00::0
      - name: anycast
        prefix: fc00:ff00::/24
        block: fc00::0
        anycast: true
  - name: N1
    netns: n1
    device: net0
    type: nat
    mode: xdpgeneric
    labels:
      natGroup: natGroup1
    segmentRoutingSrv6:
      encapSource: fc00:3100::0
      locators:
      - name: default
        prefix: fc00:3100::/24
        block: fc00::0
    configFile: |
      fib4:
      - prefix: 10.0.1.0/24
        action:
          encapSeg6:
            mode: encap
            segs: [fc00:1101::0]
      - prefix: 10.0.2.0/24
        action:
          encapSeg6:
            mode: encap
            segs: [fc00:1102::0]
  - name: N2
    netns: n2
    device: net0
    type: nat
    mode: xdpgeneric
    labels:
      natGroup: natGroup1
    segmentRoutingSrv6:
      encapSource: fc00:3200::0
      locators:
      - name: default
        prefix: fc00:3200::/24
        block: fc00::0
    configFile: |
      fib4:
      - prefix: 10.0.1.0/24
        action:
          encapSeg6:
            mode: encap
            segs: [fc00:1101::0]
      - prefix: 10.0.2.0/24
        action:
          encapSeg6:
            mode: encap
            segs: [fc00:1102::0]
  - name: N3
    netns: n3
    device: net0
    type: nat
    mode: xdpgeneric
    labels:
      natGroup: natGroup1
    segmentRoutingSrv6:
      encapSource: fc00:3300::0
      locators:
      - name: default
        prefix: fc00:3300::/24
        block: fc00::0
    configFile: |
      fib4:
      - prefix: 10.0.1.0/24
        action:
          encapSeg6:
            mode: encap
            segs: [fc00:1101::0]
      - prefix: 10.0.2.0/24
        action:
          encapSeg6:
            mode: encap
            segs: [fc00:1102::0]
  # - name: N4
  #   netns: n4
  #   device: net0
  #   type: nat
  #   mode: xdpgeneric
  #   labels:
  #     natGroup: natGroup1
  #   segmentRoutingSrv6:
  #     encapSource: fc00:3400::0
  #     locators:
  #     - name: default
  #       prefix: fc00:3400::/24
  #       block: fc00::0
  #   configFile: |
  #     fib4:
  #     - prefix: 10.0.1.0/24
  #       action:
  #         encapSeg6:
  #           mode: encap
  #           segs: [fc00:1101::0]
  #     - prefix: 10.0.2.0/24
  #       action:
  #         encapSeg6:
  #           mode: encap
  #           segs: [fc00:1102::0]
  # - name: N5
  #   netns: n5
  #   device: net0
  #   type: nat
  #   mode: xdpgeneric
  #   labels:
  #     natGroup: natGroup1
  #   segmentRoutingSrv6:
  #     encapSource: fc00:3500::0
  #     locators:
  #     - name: default
  #       prefix: fc00:3500::/24
  #       block: fc00::0
  #   configFile: |
  #     fib4:
  #     - prefix: 10.0.1.0/24
  #       action:
  #         encapSeg6:
  #           mode: encap
  #           segs: [fc00:1101::0]
  #     - prefix: 10.0.2.0/24
  #       action:
  #         encapSeg6:
  #           mode: encap
  #           segs: [fc00:1102::0]
  # - name: N6
  #   netns: n6
  #   device: net0
  #   type: nat
  #   mode: xdpgeneric
  #   labels:
  #     natGroup: natGroup1
  #   segmentRoutingSrv6:
  #     encapSource: fc00:3600::0
  #     locators:
  #     - name: default
  #       prefix: fc00:3600::/24
  #       block: fc00::0
  #   configFile: |
  #     fib4:
  #     - prefix: 10.0.1.0/24
  #       action:
  #         encapSeg6:
  #           mode: encap
  #           segs: [fc00:1101::0]
  #     - prefix: 10.0.2.0/24
  #       action:
  #         encapSeg6:
  #           mode: encap
  #           segs: [fc00:1102::0]
  # - name: N7
  #   netns: n7
  #   device: net0
  #   type: nat
  #   mode: xdpgeneric
  #   labels:
  #     natGroup: natGroup1
  #   segmentRoutingSrv6:
  #     encapSource: fc00:3700::0
  #     locators:
  #     - name: default
  #       prefix: fc00:3700::/24
  #       block: fc00::0
  #   configFile: |
  #     fib4:
  #     - prefix: 10.0.1.0/24
  #       action:
  #         encapSeg6:
  #           mode: encap
  #           segs: [fc00:1101::0]
  #     - prefix: 10.0.2.0/24
  #       action:
  #         encapSeg6:
  #           mode: encap
  #           segs: [fc00:1102::0]
  # - name: N8
  #   netns: n8
  #   device: net0
  #   type: nat
  #   mode: xdpgeneric
  #   labels:
  #     natGroup: natGroup1
  #   segmentRoutingSrv6:
  #     encapSource: fc00:3800::0
  #     locators:
  #     - name: default
  #       prefix: fc00:3800::/24
  #       block: fc00::0
  #   configFile: |
  #     fib4:
  #     - prefix: 10.0.1.0/24
  #       action:
  #         encapSeg6:
  #           mode: encap
  #           segs: [fc00:1101::0]
  #     - prefix: 10.0.2.0/24
  #       action:
  #         encapSeg6:
  #           mode: encap
  #           segs: [fc00:1102::0]
