apiVersion: mfplane.mfplane.io/v1alpha1
kind: Nat
metadata:
  labels:
    app.kubernetes.io/name: nat
    app.kubernetes.io/instance: nat-sample
    app.kubernetes.io/part-of: cplane
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cplane
  name: nat-sample1
spec:
  vip: 142.0.0.1
  sources:
  - 10.0.1.0/24
  natPortHashBit: 0x00ff
  natMapping: endpointIndependentMapping
  natFiltering: endpointIndependentFiltering
  uSidBlockLength: 16
  uSidFunctionLength: 16
  loadBalancer:
    replicas: 1
    selector:
      matchLabels:
        lbGroup: lbGroup1
  networkFunction:
    replicas: 3
    selector:
      matchLabels:
        natGroup: natGroup1
