apiVersion: mfplane.mfplane.io/v1alpha1
kind: Srv6Segment
metadata:
  name: group1-seg1
spec:
  locator: "default"
  endMfnNat:
    vip: 142.0.0.1
    sources:
    - 10.0.1.0/24
    natPortHashBit: 255
    uSidBlockLength: 16
    uSidFunctionLength: 16
  selector:
    matchLabels:
      group: group1
---
apiVersion: mfplane.mfplane.io/v1alpha1
kind: Srv6Segment
metadata:
  name: group1-seg2
spec:
  locator: "default"
  endMfnNat:
    vip: 142.0.0.1
    sources:
    - 10.0.1.0/24
    natPortHashBit: 255
    uSidBlockLength: 16
    uSidFunctionLength: 16
  selector:
    matchLabels:
      group: group1
