apiVersion: v1
items:
- apiVersion: mfplane.mfplane.io/v1alpha1
  kind: Node
  metadata:
    name: node017
    namespace: default
  spec:
    functions:
    - device: eth0
      labels:
        lbGroup: lbGroup1
        lbMaxBackends: '7'
        lbMaxRules: '2'
      mode: xdpgeneric
      name: l1
      netns: l1
      segmentRoutingSrv6:
        encapSource: fc00:0100::0
        locators:
        - block: fc00::0
          name: default
          prefix: fc00:0100::/24
        - anycast: true
          block: fc00::0
          name: anycast
          prefix: fc00:ff00::/24
      type: clb
    hostname: node017
- apiVersion: mfplane.mfplane.io/v1alpha1
  kind: Node
  metadata:
    name: node018
    namespace: default
  spec:
    functions:
    - configFile: "fib4:\n- action:\n    encapSeg6:\n      mode: encap\n      segs:\n\
        \      - 2001:a:6:2782::0\n  prefix: 10.1.0.1/32\n- action:\n    encapSeg6:\n\
        \      mode: encap\n      segs:\n      - 2001:a:7:2782::0\n  prefix: 10.1.0.2/32\n\
        - action:\n    encapSeg6:\n      mode: encap\n      segs:\n      - 2001:a:8:2782::0\n\
        \  prefix: 10.1.0.3/32\n- action:\n    encapSeg6:\n      mode: encap\n   \
        \   segs:\n      - 2001:a:9:2782::0\n  prefix: 10.1.0.4/32\n- action:\n  \
        \  encapSeg6:\n      mode: encap\n      segs:\n      - 2001:a:11:2782::0\n\
        \  prefix: 10.1.0.5/32\n- action:\n    encapSeg6:\n      mode: encap\n   \
        \   segs:\n      - 2001:a:12:2782::0\n  prefix: 10.1.0.6/32\n- action:\n \
        \   encapSeg6:\n      mode: encap\n      segs:\n      - 2001:a:13:2782::0\n\
        \  prefix: 10.1.0.7/32\n- action:\n    encapSeg6:\n      mode: encap\n   \
        \   segs:\n      - 2001:a:14:2782::0\n  prefix: 10.1.0.8/32\n- action:\n \
        \   encapSeg6:\n      mode: encap\n      segs:\n      - 2001:a:15:2782::0\n\
        \  prefix: 10.1.0.9/32\n- action:\n    encapSeg6:\n      mode: encap\n   \
        \   segs:\n      - 2001:a:16:2782::0\n  prefix: 10.1.0.10/32\n"
      device: eth0
      labels:
        natGroup: natGroup1
      mode: xdpgeneric
      name: n1
      netns: n1
      segmentRoutingSrv6:
        encapSource: fc00:0200::0
        locators:
        - block: fc00::0
          name: default
          prefix: fc00:0200::/24
      type: nat
    hostname: node018
kind: List
metadata:
  resourceVersion: ''
