apiVersion: v1
items:
- apiVersion: mfplane.mfplane.io/v1alpha1
  kind: Node
  metadata:
    name: node010
    namespace: default
  spec:
    functions:
    - device: eth0
      labels:
        lbGroup: lbGroup1
        lbMaxBackends: '7'
        lbMaxRules: '2'
      mode: xdpgeneric
      name: l1
      netns: l1
      segmentRoutingSrv6:
        encapSource: fc01:0100::0
        locators:
        - block: fc00::0
          name: default
          prefix: fc01:0100::/24
        - anycast: true
          block: fc00::0
          name: anycast
          prefix: fc00:ff00::/24
      type: clb
    hostname: node010
- apiVersion: mfplane.mfplane.io/v1alpha1
  kind: Node
  metadata:
    name: node011
    namespace: default
  spec:
    functions:
    - device: eth0
      labels:
        lbGroup: lbGroup1
        lbMaxBackends: '7'
        lbMaxRules: '2'
      mode: xdpgeneric
      name: l2
      netns: l2
      segmentRoutingSrv6:
        encapSource: fc01:0200::0
        locators:
        - block: fc00::0
          name: default
          prefix: fc01:0200::/24
        - anycast: true
          block: fc00::0
          name: anycast
          prefix: fc00:ff00::/24
      type: clb
    hostname: node011
- apiVersion: mfplane.mfplane.io/v1alpha1
  kind: Node
  metadata:
    name: node012
    namespace: default
  spec:
    functions:
    - configFile: "fib4:\n- action:\n    encapSeg6:\n      mode: encap\n      segs:\n\
        \      - 2001:a:6:2782::0\n  prefix: 10.1.0.1/32\n- action:\n    encapSeg6:\n\
        \      mode: encap\n      segs:\n      - 2001:a:7:2782::0\n  prefix: 10.1.0.2/32\n\
        - action:\n    encapSeg6:\n      mode: encap\n      segs:\n      - 2001:a:8:2782::0\n\
        \  prefix: 10.1.0.3/32\n- action:\n    encapSeg6:\n      mode: encap\n   \
        \   segs:\n      - 2001:a:9:2782::0\n  prefix: 10.1.0.4/32\n"
      device: eth0
      labels:
        natGroup: natGroup1
      mode: xdpgeneric
      name: n1
      netns: n1
      segmentRoutingSrv6:
        encapSource: fc02:0100::0
        locators:
        - block: fc00::0
          name: default
          prefix: fc02:0100::/24
      type: nat
    hostname: node012
- apiVersion: mfplane.mfplane.io/v1alpha1
  kind: Node
  metadata:
    name: node013
    namespace: default
  spec:
    functions:
    - configFile: "fib4:\n- action:\n    encapSeg6:\n      mode: encap\n      segs:\n\
        \      - 2001:a:6:2782::0\n  prefix: 10.1.0.1/32\n- action:\n    encapSeg6:\n\
        \      mode: encap\n      segs:\n      - 2001:a:7:2782::0\n  prefix: 10.1.0.2/32\n\
        - action:\n    encapSeg6:\n      mode: encap\n      segs:\n      - 2001:a:8:2782::0\n\
        \  prefix: 10.1.0.3/32\n- action:\n    encapSeg6:\n      mode: encap\n   \
        \   segs:\n      - 2001:a:9:2782::0\n  prefix: 10.1.0.4/32\n"
      device: eth0
      labels:
        natGroup: natGroup1
      mode: xdpgeneric
      name: n2
      netns: n2
      segmentRoutingSrv6:
        encapSource: fc02:0200::0
        locators:
        - block: fc00::0
          name: default
          prefix: fc02:0200::/24
      type: nat
    hostname: node013
kind: List
metadata:
  resourceVersion: ''
