apiVersion: mfplane.mfplane.io/v1alpha1
kind: Node
metadata:
  labels:
    app.kubernetes.io/name: node
    app.kubernetes.io/instance: node-sample
    app.kubernetes.io/part-of: cplane
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: cplane
  name: node-sample
spec:
  # TODO(user): Add fields here
