namePrefix: l1
maxRules: 2
maxBackends: 7
encapSource: fc00:1::0
localSids:
- sid: fc00:ff:1::/48 # NAT1
  End_MFL:
    vip: 142.0.0.1
    natPortHashBit: 0x00ff
    uSidBlock: fc00::0
    uSidBlockLength: 16
    uSidFunctionLength: 32
    uSidFunctionRevisions:
    - backends:
      - 13:1::0
    - backends:
      - 11:1::0
      - 12:1::0
