name: release binary

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          artifact_name: mikanectl
          asset_name: mikanectl.linux-amd64
    steps:
    - name: set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
      id: go
    - name: checkout
      uses: actions/checkout@v2
    - name: download modules
      if: steps.cache.outputs.cache-hit != 'true'
      run: go mod download
    - name: test
      run: go test ./... -v
    - name: build
      run: |
        go build -o ${{ matrix.artifact_name }} -ldflags "\
          -X github.com/slankdev/mfplane/pkg/util.gitSHA=$(git rev-parse HEAD) \
          -X github.com/slankdev/mfplane/pkg/util.gitBranch=none \
          -X github.com/slankdev/mfplane/pkg/util.gitTag=$(git describe --tags --abbrev=0) \
          -X github.com/slankdev/mfplane/pkg/util.buildDate=$(date '+%Y/%m/%d-%H:%M:%S-%Z') \
          " cmd/flowctl/main.go

    - name: upload
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}
        #overwrite: true
