name: release container-image
on:
  push:
    tags:
    - 'v*'

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - name: clone repo
      uses: actions/checkout@v2

    - name: login ghcr
      id: login_docker
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: slankdev
        password: ${{ secrets.GH_SECRET }}

    - name: push with branch name
      id: run_docker_push_with_branch_name
      run: |
        VERSION=$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")
        docker build \
          --build-arg GIT_SHA=$(git rev-parse HEAD) \
          --build-arg GIT_BRANCH=nona \
          --build-arg GIT_TAG=$VERSION \
          --build-arg BUILD_DATE=$(date '+%Y/%m/%d-%H:%M:%S-%Z') \
          --tag ghcr.io/slankdev/mfplane:$VERSION .
        docker push ghcr.io/slankdev/mfplane:$VERSION
      env:
        BUILDKIT: 1
